from datetime import datetime

from sqlalchemy import Column, String, Text
from sqlalchemy.dialects.postgresql import ARRAY
from sqlmodel import Field, Relationship, SQLModel, UniqueConstraint

from app.core.util import now
from app.models.organization import Organization
from app.models.project import Project


class AssistantBase(SQLModel):
    __table_args__ = (
        UniqueConstraint("project_id", "assistant_id", name="uq_project_assistant_id"),
    )

    assistant_id: str = Field(index=True)
    name: str
    instructions: str = Field(sa_column=Column(Text, nullable=False))
    model: str
    vector_store_ids: list[str] = Field(
        default_factory=list, sa_column=Column(ARRAY(String))
    )
    temperature: float = 0.1
    max_num_results: int = 20
    project_id: int = Field(
        foreign_key="project.id", nullable=False, ondelete="CASCADE"
    )
    organization_id: int = Field(
        foreign_key="organization.id", nullable=False, ondelete="CASCADE"
    )


class Assistant(AssistantBase, table=True):
    """OpenAI assistant configuration and metadata."""

    __tablename__ = "openai_assistant"

    id: int = Field(
        default=None,
        primary_key=True,
        sa_column_kwargs={"comment": "Unique identifier for the assistant"},
    )
    assistant_id: str = Field(
        index=True,
        sa_column_kwargs={"comment": "Unique identifier for the assistant at OpenAI"},
    )
    name: str = Field(
        sa_column_kwargs={"comment": "Name of the assistant"},
    )
    instructions: str = Field(
        sa_column=Column(
            Text, nullable=False, comment="System instructions for the assistant"
        )
    )
    model: str = Field(
        sa_column_kwargs={"comment": "OpenAI model used by the assistant"},
    )
    vector_store_ids: list[str] = Field(
        default_factory=list,
        sa_column=Column(
            ARRAY(String), comment="List of OpenAI vector store IDs attached"
        ),
    )
    temperature: float = Field(
        default=0.1,
        sa_column_kwargs={
            "comment": "Parameter that controls the creativity or randomness of the text generated by model"
        },
    )
    max_num_results: int = Field(
        default=20,
        sa_column_kwargs={
            "comment": "Parameter that controls maximum number of results to return"
        },
    )
    # Foreign keys
    project_id: int = Field(
        foreign_key="project.id",
        nullable=False,
        ondelete="CASCADE",
        sa_column_kwargs={"comment": "Reference to the project"},
    )
    organization_id: int = Field(
        foreign_key="organization.id",
        nullable=False,
        ondelete="CASCADE",
        sa_column_kwargs={"comment": "Reference to the organization"},
    )

    # Timestamps
    inserted_at: datetime = Field(
        default_factory=now,
        nullable=False,
        sa_column_kwargs={"comment": "Timestamp when the assistant was created"},
    )
    updated_at: datetime = Field(
        default_factory=now,
        nullable=False,
        sa_column_kwargs={"comment": "Timestamp when the assistant was last updated"},
    )
    deleted_at: datetime | None = Field(
        default=None,
        nullable=True,
        sa_column_kwargs={"comment": "Timestamp when the assistant was deleted"},
    )

    # Relationships
    project: Project = Relationship(back_populates="assistants")
    organization: Organization = Relationship(back_populates="assistants")


class AssistantCreate(SQLModel):
    name: str = Field(description="Name of the assistant", min_length=3, max_length=50)
    instructions: str = Field(
        description="Instructions for the assistant", min_length=10
    )
    assistant_id: str | None = Field(
        default=None,
        description="Unique identifier for the assistant",
        min_length=3,
        max_length=50,
    )
    model: str = Field(
        default="gpt-4o",
        description="Model name for the assistant",
        min_length=1,
        max_length=50,
    )
    vector_store_ids: list[str] = Field(
        default_factory=list,
        description="List of Vector Store IDs that exist in OpenAI.",
    )
    temperature: float = Field(
        default=0.1, ge=0, le=2, description="Sampling temperature between 0 and 2"
    )
    max_num_results: int = Field(
        default=20,
        ge=1,
        le=100,
        description="Maximum number of results (must be between 1 and 100)",
    )


class AssistantUpdate(SQLModel):
    name: str | None = Field(
        default=None, description="Name of the assistant", min_length=3, max_length=50
    )
    instructions: str | None = Field(
        default=None,
        description="Instructions for the assistant",
        min_length=10,
    )
    model: str | None = Field(
        default=None, description="Name of the model", min_length=1, max_length=50
    )
    vector_store_ids_add: list[str] | None = None
    vector_store_ids_remove: list[str] | None = None
    temperature: float | None = Field(
        default=None, ge=0, le=2, description="Sampling temperature between 0 and 2"
    )
    max_num_results: int | None = Field(
        default=None,
        ge=1,
        le=100,
        description="Maximum number of results (must be between 1 and 100)",
    )
