import re
from datetime import datetime

from pydantic import field_validator
from sqlmodel import Field, Relationship, SQLModel

from app.core.util import now
from app.models.organization import Organization
from app.models.project import Project


def validate_response_id_pattern(v: str) -> str:
    """Shared validation function for response ID patterns"""
    if v is None:
        return v
    if not re.match(r"^resp_[a-zA-Z0-9]{10,}$", v):
        raise ValueError(
            "response_id fields must follow pattern: resp_ followed by at least 10 alphanumeric characters"
        )
    return v


class OpenAIConversationBase(SQLModel):
    # usually follow the pattern of resp_688704e41190819db512c30568xxxxxxx
    response_id: str = Field(
        index=True,
        min_length=10,
        sa_column_kwargs={"comment": "OpenAI response identifier"},
    )
    ancestor_response_id: str = Field(
        index=True,
        description="Ancestor response ID for conversation threading",
        sa_column_kwargs={"comment": "Root response ID for conversation threading"},
    )
    previous_response_id: str | None = Field(
        default=None,
        index=True,
        description="Previous response ID in the conversation",
        sa_column_kwargs={"comment": "Previous response ID in the conversation chain"},
    )
    user_question: str = Field(
        description="User's question/input",
        sa_column_kwargs={"comment": "User's question or input text"},
    )
    response: str | None = Field(
        default=None,
        description="AI response",
        sa_column_kwargs={"comment": "Response generated by OpenAI"},
    )
    # there are models with small name like o1 and usually fine tuned models have long names
    model: str = Field(
        description="The model used for the response",
        min_length=1,
        max_length=150,
        sa_column_kwargs={"comment": "Model used to generate the response"},
    )
    # usually follow the pattern of asst_WD9bumYqTtpSvxxxxx
    assistant_id: str | None = Field(
        default=None,
        description="The assistant ID used",
        min_length=10,
        max_length=50,
        sa_column_kwargs={"comment": "OpenAI assistant identifier if used"},
    )
    project_id: int = Field(
        foreign_key="project.id",
        nullable=False,
        ondelete="CASCADE",
        sa_column_kwargs={"comment": "Reference to the project"},
    )
    organization_id: int = Field(
        foreign_key="organization.id",
        nullable=False,
        ondelete="CASCADE",
        sa_column_kwargs={"comment": "Reference to the organization"},
    )

    @field_validator("response_id", "ancestor_response_id", "previous_response_id")
    @classmethod
    def validate_response_ids(cls, v):
        return validate_response_id_pattern(v)


class OpenAIConversation(OpenAIConversationBase, table=True):
    """Stores OpenAI conversation history and responses."""

    __tablename__ = "openai_conversation"

    id: int = Field(
        default=None,
        primary_key=True,
        sa_column_kwargs={"comment": "Unique identifier for the conversation record"},
    )
    # Timestamps
    inserted_at: datetime = Field(
        default_factory=now,
        nullable=False,
        sa_column_kwargs={"comment": "Timestamp when the conversation was created"},
    )
    updated_at: datetime = Field(
        default_factory=now,
        nullable=False,
        sa_column_kwargs={
            "comment": "Timestamp when the conversation was last updated"
        },
    )
    deleted_at: datetime | None = Field(
        default=None,
        nullable=True,
        sa_column_kwargs={"comment": "Timestamp when the conversation was deleted"},
    )

    # Relationships
    project: Project = Relationship(back_populates="openai_conversations")
    organization: Organization = Relationship(back_populates="openai_conversations")


class OpenAIConversationCreate(SQLModel):
    # usually follow the pattern of resp_688704e41190819db512c30568dcaebc0a42e02be2c2c49b
    response_id: str = Field(min_length=10)
    ancestor_response_id: str = Field(
        description="Ancestor response ID for conversation threading"
    )
    previous_response_id: str | None = Field(
        default=None, description="Previous response ID in the conversation"
    )
    user_question: str = Field(description="User's question/input", min_length=1)
    response: str | None = Field(default=None, description="AI response")
    # there are models with small name like o1 and usually fine tuned models have long names
    model: str = Field(
        description="The model used for the response", min_length=1, max_length=150
    )
    # usually follow the pattern of asst_WD9bumYqTtpSvxxxxx
    assistant_id: str | None = Field(
        default=None,
        description="The assistant ID used",
        min_length=10,
        max_length=50,
    )

    @field_validator("response_id", "ancestor_response_id", "previous_response_id")
    @classmethod
    def validate_response_ids(cls, v):
        return validate_response_id_pattern(v)


class OpenAIConversationPublic(OpenAIConversationBase):
    """Public model for OpenAIConversation without sensitive fields"""

    id: int
    inserted_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
        populate_by_name = True
        use_enum_values = True
