"""Assessment models package.

Split by surface: ``assessment.py`` (shared tables/enums + legacy RUN UI),
``assessment_api.py`` (``/assessments`` request/response), ``submission.py`` (uploaded
submission files). All re-exported here, so ``from app.models.assessment import X`` works.
"""

from app.models.assessment.assessment import (
    Assessment,
    AssessmentAttachment,
    AssessmentConfigRef,
    AssessmentExecutionPublic,
    AssessmentExportRow,
    AssessmentMethod,
    AssessmentPublic,
    AssessmentResponse,
    AssessmentRun,
    AssessmentRunCounts,
    AssessmentRunCreate,
    AssessmentRunOverview,
    AssessmentRunPublic,
    AssessmentRunResponse,
    AssessmentRunStat,
    AssessmentRunSummary,
    AssessmentStatus,
    InputBinding,
    RunExecution,
    Stage,
    StageStatus,
)
from app.models.assessment.assessment_api import (
    AssessmentBatchResult,
    AssessmentCallback,
    AssessmentCounts,
    AssessmentCreate,
    AssessmentInput,
    AssessmentOutput,
    AssessmentResult,
    AssessmentResultData,
    AssessmentSubmitResponse,
    Attachment,
    BatchInput,
    BatchRunState,
    ParsedResult,
    PreFilter,
    PreFilterVerdict,
    ResponseInput,
    Submission,
    Verdict,
    derive_method,
)
from app.models.assessment.submission import (
    AssessmentSubmission,
    AssessmentSubmissionPreview,
    AssessmentSubmissionResponse,
)

__all__ = [
    # shared tables + enums
    "Assessment",
    "AssessmentRun",
    "AssessmentMethod",
    "AssessmentStatus",
    "AssessmentConfigRef",
    # legacy RUN (UI) surface
    "Stage",
    "StageStatus",
    "AssessmentAttachment",
    "InputBinding",
    "RunExecution",
    "AssessmentExecutionPublic",
    "AssessmentResponse",
    "AssessmentPublic",
    "AssessmentExportRow",
    "AssessmentRunCreate",
    "AssessmentRunCounts",
    "AssessmentRunStat",
    "AssessmentRunSummary",
    "AssessmentRunPublic",
    "AssessmentRunResponse",
    "AssessmentRunOverview",
    # uploaded submission files
    "AssessmentSubmission",
    "AssessmentSubmissionPreview",
    "AssessmentSubmissionResponse",
    # API-client surface
    "Attachment",
    "ResponseInput",
    "BatchInput",
    "BatchRunState",
    "ParsedResult",
    "Verdict",
    "Submission",
    "AssessmentInput",
    "derive_method",
    "AssessmentCreate",
    "AssessmentSubmitResponse",
    "AssessmentCallback",
    "PreFilterVerdict",
    "PreFilter",
    "AssessmentOutput",
    "AssessmentResult",
    "AssessmentCounts",
    "AssessmentBatchResult",
    "AssessmentResultData",
]
