"""remove:enum checks llm_call provider

Revision ID: 044
Revises: 043
Create Date: 2026-01-30 11:22:45.165543

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "044"
down_revision = "043"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "llm_call",
        "provider",
        existing_type=sa.VARCHAR(),
        comment="AI provider as sent by user (e.g openai, -native, google)",
        existing_comment="AI provider: openai, google, anthropic",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "llm_call",
        "provider",
        existing_type=sa.VARCHAR(),
        comment="AI provider: openai, google, anthropic",
        existing_comment="AI provider as sent by user (e.g openai, -native, google)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
