#!/usr/bin/env sh
#
# Fetch one or more JSON secrets from AWS Secrets Manager and write them as a
# docker-compose env_file (.env.secrets). Run on the EC2 host at deploy time,
# BEFORE `docker compose up`. Never run at image build time — that would bake
# secrets into image layers.
#
# Auth: relies on the EC2 instance IAM role (no static AWS keys).
#
# Required env:
#   SECRET_ID            Comma-separated secret names or ARNs, e.g.
#                        "kaapi-staging-rds, kaapi-staging-rabbitmq".
#                        Secrets are appended in order; on a duplicate key the
#                        last secret wins (docker compose reads the last line).
# Optional env:
#   AWS_DEFAULT_REGION   AWS region (default: ap-south-1)
#   SECRETS_ENV_FILE     Output path (default: .env.secrets)

set -e

SECRET_IDS=${SECRET_ID:?SECRET_ID not set}
AWS_REGION=${AWS_DEFAULT_REGION:-ap-south-1}
OUT=${SECRETS_ENV_FILE:-.env.secrets}

command -v aws >/dev/null 2>&1 || { echo "[fetch-secrets] aws CLI not found on host" >&2; exit 1; }
command -v jq  >/dev/null 2>&1 || { echo "[fetch-secrets] jq not found on host" >&2; exit 1; }

umask 077
TMP="${OUT}.tmp"
printf '# Generated by fetch-secrets.sh — do not edit, do not commit.\n' > "${TMP}"

OLD_IFS=$IFS
IFS=','
for ID in ${SECRET_IDS}; do
  # Secret names and ARNs never contain whitespace, so " a, b" splits cleanly.
  ID=$(printf '%s' "${ID}" | tr -d '[:space:]')
  [ -n "${ID}" ] || continue

  echo "[fetch-secrets] Fetching secret | id: ${ID} | region: ${AWS_REGION}"
  SECRET_JSON=$(aws secretsmanager get-secret-value \
    --secret-id "${ID}" \
    --region "${AWS_REGION}" \
    --query SecretString --output text)
  echo "${SECRET_JSON}" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> "${TMP}"
done
IFS=$OLD_IFS

mv "${TMP}" "${OUT}"

COUNT=$(grep -c '=' "${OUT}")
echo "[fetch-secrets] Wrote ${COUNT} keys | file: ${OUT}"
