#!/usr/bin/env sh
#
# Fetch a JSON secret from AWS Secrets Manager and write it as a docker-compose
# env_file (.env.secrets). Run on the EC2 host at deploy time, BEFORE
# `docker compose up`. Never run at image build time — that would bake secrets
# into image layers.
#
# Auth: relies on the EC2 instance IAM role (no static AWS keys).
#
# Required env:
#   SECRET_ID            Secret name or ARN, e.g. kaapi/staging
# Optional env:
#   AWS_DEFAULT_REGION   AWS region (default: ap-south-1)
#   SECRETS_ENV_FILE     Output path (default: .env.secrets)

set -e

SECRET_ID=${SECRET_ID:?SECRET_ID not set}
AWS_REGION=${AWS_DEFAULT_REGION:-ap-south-1}
OUT=${SECRETS_ENV_FILE:-.env.secrets}

command -v aws >/dev/null 2>&1 || { echo "[fetch-secrets] aws CLI not found on host" >&2; exit 1; }
command -v jq  >/dev/null 2>&1 || { echo "[fetch-secrets] jq not found on host" >&2; exit 1; }

echo "[fetch-secrets] Fetching secret | id: ${SECRET_ID} | region: ${AWS_REGION}"

SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "${SECRET_ID}" \
  --region "${AWS_REGION}" \
  --query SecretString --output text)

# Render JSON object -> KEY=value lines. docker compose env_file parses these
# literally (no shell expansion), so raw values are written as-is.
umask 077
printf '# Generated by fetch-secrets.sh — do not edit, do not commit.\n' > "${OUT}"
echo "${SECRET_JSON}" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> "${OUT}"

COUNT=$(echo "${SECRET_JSON}" | jq 'length')
echo "[fetch-secrets] Wrote ${COUNT} keys | file: ${OUT}"
